### ISSUE TITLE
oclID and backslash

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#129]
There is an issue generating oclID. An oclID can contain all the ascii code from 32 to 127. In this range we have 'backslash' as well as DEL (ascii 127).

The problem is that if we have a string containing a backslash following by `a` for example that backslash symbol is removed if you make a JSON.stringify().

`JSON.stringify('\a') -> 'a'`
`JSON.stringify('\b') -> '\\b'`

@targos I don't see how to solve this issue. Should we 'escape' / 'unescape' (or URLencode) the oclID ?

Here is a molecule for which we have problems by storing in mongoDB and trying to search it back

`fdy@p@@DLxL\bbbfbRRbkAZ|uHTCQT@@@`

oclID can be displayed [here](https://www.cheminfo.org/?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F1cc9e892242664b1d5a37312bda159ef%2Fview.json&loadversion=true&fillsearch=Display+OCLcode+oclID).

**Comment by lpatiny** [comment]
@targos we can discuss tomorrow I still need to investigate.

**Comment by targos** [comment]
When you do `JSON.stringify('\a')`, there is actually no backslash in the string that you pass to JSON.stringify (because the backslash is already "consumed").
Do you have a real problematic example? In JS, if you JSON.stringify a string that contains a backslash, two backslashes should be added to take it into account:

![image](https://user-images.githubusercontent.com/2352663/167815012-338d2123-95a6-4968-bf68-de9bb62b5808.png)

**Comment by targos** [comment]
@lpatiny is this still an issue?

**Comment by targos** [comment]
Ping @lpatiny

**Comment by lpatiny** [comment]
No it was our mistake copying from the console.log
