### ISSUE TITLE
Clean-up alignment issue

### ISSUE THREAD

**Issue by BobHanson** [cheminfo/openchemlib-js#158]
Clicking the structure-clean button doesn't just clean up the structure; it can completely reorient it. Is there code in openchemlib that would allow the cleaned up structure to be aligned with the original?

**Comment by targos** [comment]
This is an issue for https://github.com/actelion/openchemlib

**Comment by targos** [comment]
`openchemlib` is the original Java library.
`openchemlib-js` is a separate project by a different group of developers. We include a copy of `openchemlib` and make some modifications to the code so it can be compiled using GWT. Then we have a few custom classes that make the glue between the Java and the JavaScript code.
Issues about functional problems are most likely suited to the `openchemlib` project because we try not to make any functional change here and rather just expose an wrapper API for JavaScript developers.
In this project, issues should be about either missing features that currently are only available in the Java library or bugs in the JS<->Java interaction.

**Comment by BobHanson** [comment]
OK. Thank you. That's very helpful. I'm instead using java2acript/SwingJS
<https://github.com/BobHanson/OCL-SwingJS>. I'm sure you have no interest
in that. But it doesn't have the limitations and special classes of GWT,
and it adds dynamic class loading and GUI. And it doesn't affect Java
functionality at all. So since that does not have anything to do with GWT,
I won't post here.

Thanks again. I guess as long as you are satisfied with what you have and
are monitoring the Java issues yourself, I won't bother you with them.
